//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLYX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Log
    {
        public string LogId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SourceObjectId { get; set; }
        public string SourceContentJson { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string OperateUserId { get; set; }
        public string OperateAccount { get; set; }
        public string OperateTypeId { get; set; }
        public string OperateType { get; set; }
        public string ModuleId { get; set; }
        public string Module { get; set; }
        public string IPAddress { get; set; }
        public string IPAddressName { get; set; }
        public string Host { get; set; }
        public string Browser { get; set; }
        public Nullable<int> ExecuteResult { get; set; }
        public string ExecuteResultJson { get; set; }
        public string Description { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<int> EnabledMark { get; set; }
    }
}
